### ISSUE TITLE
MacOS GUI

### ISSUE THREAD

**Issue by b0balagurak** [mucsci-students/2023sp-420-SNEK#149]
- [x] Make the design in MacOs similar to the windows one
 - [x] If necessary, make changes in the GUI

 
 - Primary: @b0balagurak
 - Secondary: @Joperezc 
 - Size: LARGE
 - Actual Size: SMALL
 - Actual Time: ~1.5 Hours

**Comment by nrhoopes** [comment]
MacOS on light mode looks as similar to windows as possible without using a completely different library and wasting unnecessary space by making a separate implementation.
