### ISSUE TITLE
Implement design patterns

### ISSUE THREAD

**Issue by AitorCantero** [mucsci-students/2023sp-420-SNEK#154]
Implement design patterns
 
 - [x] Decide on the rest of patterns to be implemented
 - [x] Design their in implementation in the project
 - [x] Implement them
 - [x] Document tehm in the ReadMe
 
 - Primary: @AitorCantero
 - Secondary: @nrhoopes
 - Secondary: @Joperezc
 - Secondary: @aermenllanos
 - Secondary: @SClugston9
 - Secondary: @b0balagurak
 - Size: LARGE
 - Actual Size: LARGE
 - Actual Time: ~5 Hours

**Comment by nrhoopes** [comment]
First 5 design patterns added to the README.
