### ISSUE TITLE
CLI: Tab Completion

### ISSUE THREAD

**Issue by AitorCantero** [mucsci-students/2023sp-420-SNEK#157]
- [x] Design/implement a distance function to get the next most similar completion string
- [x] Pressing tab midway through typing a command will autocomplete the command
- [x] Pressing tab will highlight/make a list the autofill so that it is easier to see.

Primary: @AitorCantero
Secondary: @SClugston9

Size: LARGE

Actual Size: XXL

Actual Time: 16 Hours (including 2 refactors)

**Comment by nrhoopes** [comment]
Due to the outlaw of the keyboard module, Tab Completion will need to be reworked.  Current working implementation requires three different modules dependent on operating system, and each implementation has different behavior depending on operating system.

**Comment by nrhoopes** [comment]
New implementation has been added.  Tab complete now gives a drop-down list that you can tab through to auto complete your command in the terminal.
