### ISSUE TITLE
Please streamline the user experience

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-SNEK#68]
1. Ensure every area where text can be entered that this user is aware of what input is accepted.
2. Do not force the user to "press enter to continue" at any point in time. The user doesn't want to have to repeatedly press enter.

**Comment by willkill07** [comment]
?

**Comment by nrhoopes** [comment]
User no longer has to press enter when being asked yes or no to exiting and saving.  User also can now tab complete scratch/current when deciding type of save.

**Comment by nrhoopes** [comment]
Unfortunately, the use of the keyboard module was outlawed and as a result this issue will need to be reworked.

**Comment by nrhoopes** [comment]
New implementation has been added to handle y/n/c without the need for admin privs.  Tab complete now also works and gives a drop down list to tab through to auto complete your option.
