### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by b0balagurak** [mucsci-students/2023sp-420-SNEK#72]
''' Build System
 
 - [x] Build system should create a virtual environment
 - [x] Build system should install any needed libraries
 - [x] Build system should initialize any databases
 - [x] Build system should run tests
 - [x] Build system should throw error for test error
 - [x] Build system should throw error for library installation error
 - [x] Build system should throw error for database errors
 
 - Primary: @Joperezc
 - Secondary: @SClugston9
 - Size: MEDIUM
 - Actual Size: LARGE
 - Actual Time: 3HR 30MIN'''

**Comment by Joperezc** [comment]
Build system currently working, will update again once refactor and GUI are finished to check for any issues
