### ISSUE TITLE
Fix Readme - it's got too much infor

### ISSUE THREAD

**Issue by SClugston9** [mucsci-students/2023sp-420-SNEK#77]
- [x] Update readme to remove useless information like the specific file libraries etc.
 
 - Primary: @Joperezc
 - Secondary: @nrhoopes
 - Size: XSMALL
 - Actual Size:
 - Actual Time:

**Comment by Joperezc** [comment]
Made an inital readme revision, will edit near the due date to better reflect final sprint 2 product

**Comment by Joperezc** [comment]
Edited readme to reflect final version
