### ISSUE TITLE
GUI: Load

### ISSUE THREAD

**Issue by SClugston9** [mucsci-students/2023sp-420-SNEK#79]
''' Load Button and Functionality for GUI
 
 - [x] Load Button Visible
 - [x] Display all save files when pressed
 - [x] If game is open ask to save
 - [x] if saving, save and load after
 - [x] if not saving, just load
 
 - Primary: @Joperezc
 - Secondary: @nrhoopes
 - Size: Medium
 - Actual Size: Medium
 - Actual Time: 4HR

**Comment by Joperezc** [comment]
Made with File Diag, using tkinter, in game found in a menu option, in Main Menu found as button
