### ISSUE TITLE
Save and Load: New Json

### ISSUE THREAD

**Issue by AitorCantero** [mucsci-students/2023sp-420-SNEK#80]
Save and Load: New Json
 
 - [x] Save Parse New Json

 
 - Primary: @Joperezc
 - Secondary: @nrhoopes
 - Size: MEDIUM
 - Actual Size: MEDIUM
 - Actual Time: 1HR 30MIN

**Comment by Joperezc** [comment]
Updated Json parse in the form 
{guessedWords, wordList, puzzleLetters, requiredLetter, currentPoints, maxPoints}
