### ISSUE TITLE
Save Game

### ISSUE THREAD

**Issue by SClugston9** [mucsci-students/2023sp-420-SNEK#87]
- [x] When a Puzzle is open, if the save button is hovered over, current or scratch will be options
 - [x] When no Puzzle is loaded, the save button will be grayed out and unusable.
 
 - Primary: @nrhoopes
 - Secondary: @Joperezc
 - Size: MEDIUM
 - Actual Size: MEDIUM
 - Actual Time: 4HR

**Comment by Joperezc** [comment]
Easier originally, adding save filedialog made the task slightly more difficult
